openapi: 3.0.3
info:
  title: Eternal AI API
  description: Eternal AI API description
  version: v1
components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas: {}
paths:
  /sign-up:
    post:
      tags:
        - user
      description: Sign up
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 8
                  maxLength: 32
                  pattern: ^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d!@#$%^&*()-_=+\\|{}\[\];:,.<>\/?`~]+$
              required:
                - email
                - password
        required: true
      responses:
        "201":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                        format: uuid
                      email:
                        type: string
                        format: email
                    required:
                      - id
                      - email
                  success:
                    type: boolean
                required:
                  - success
        "400":
          description: |-
            Available messages:

            • BAD_REQUEST
          content:
            application/json:
              schema:
                type: object
                description: |-
                  Available messages:

                  • BAD_REQUEST
                properties:
                  message:
                    type: string
                  success:
                    type: boolean
                required:
                  - message
                  - success
        "409":
          description: |-
            Available messages:

            • USER_WITH_SUCH_EMAIL_ALREADY_EXISTS
          content:
            application/json:
              schema:
                type: object
                description: |-
                  Available messages:

                  • USER_WITH_SUCH_EMAIL_ALREADY_EXISTS
                properties:
                  message:
                    type: string
                  success:
                    type: boolean
                required:
                  - message
                  - success
  /sign-in:
    post:
      tags:
        - user
      description: Sign in
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 8
                  maxLength: 32
                  pattern: ^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d!@#$%^&*()-_=+\\|{}\[\];:,.<>\/?`~]+$
              required:
                - email
                - password
        required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  token:
                    type: string
                  success:
                    type: boolean
                required:
                  - token
                  - success
        "400":
          description: |-
            Available messages:

            • BAD_REQUEST

            • PASSWORD_IS_INCORRECT

            • USER_WAS_REGISTERED_WITH_ANOTHER_METHOD
          content:
            application/json:
              schema:
                type: object
                description: |-
                  Available messages:

                  • BAD_REQUEST

                  • PASSWORD_IS_INCORRECT

                  • USER_WAS_REGISTERED_WITH_ANOTHER_METHOD
                properties:
                  message:
                    type: string
                  success:
                    type: boolean
                required:
                  - message
                  - success
        "404":
          description: |-
            Available messages:

            • USER_NOT_FOUND
          content:
            application/json:
              schema:
                type: object
                description: |-
                  Available messages:

                  • USER_NOT_FOUND
                properties:
                  message:
                    type: string
                  success:
                    type: boolean
                required:
                  - message
                  - success
  /google/auth:
    get:
      tags:
        - user
      description: Google auth
      parameters:
        - schema:
            type: string
          in: query
          name: code
          required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  token:
                    type: string
                  success:
                    type: boolean
                required:
                  - token
                  - success
        "400":
          description: |-
            Available messages:

            • USER_WAS_REGISTERED_WITH_ANOTHER_METHOD
          content:
            application/json:
              schema:
                type: object
                description: |-
                  Available messages:

                  • USER_WAS_REGISTERED_WITH_ANOTHER_METHOD
                properties:
                  message:
                    type: string
                  success:
                    type: boolean
                required:
                  - message
                  - success
  /forgot-password-send:
    post:
      tags:
        - user
      description: Forgot password send
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                email:
                  type: string
                  format: email
              required:
                - email
        required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  message:
                    type: string
                  success:
                    type: boolean
                required:
                  - message
                  - success
        "400":
          description: |-
            Available messages:

            • BAD_REQUEST
          content:
            application/json:
              schema:
                type: object
                description: |-
                  Available messages:

                  • BAD_REQUEST
                properties:
                  message:
                    type: string
                  success:
                    type: boolean
                required:
                  - message
                  - success
        "403":
          description: |-
            Available messages:

            • FORBIDDEN
          content:
            application/json:
              schema:
                type: object
                description: |-
                  Available messages:

                  • FORBIDDEN
                properties:
                  message:
                    type: string
                  success:
                    type: boolean
                required:
                  - message
                  - success
        "404":
          description: |-
            Available messages:

            • USER_NOT_FOUND
          content:
            application/json:
              schema:
                type: object
                description: |-
                  Available messages:

                  • USER_NOT_FOUND
                properties:
                  message:
                    type: string
                  success:
                    type: boolean
                required:
                  - message
                  - success
  /forgot-password-change:
    post:
      tags:
        - user
      description: Forgot password change
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                email:
                  type: string
                  format: email
                token:
                  type: string
                password:
                  type: string
                  minLength: 8
                  maxLength: 32
                  pattern: ^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d!@#$%^&*()-_=+\\|{}\[\];:,.<>\/?`~]+$
              required:
                - email
                - token
                - password
        required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  message:
                    type: string
                  success:
                    type: boolean
                required:
                  - message
                  - success
        "400":
          description: |-
            Available messages:

            • BAD_REQUEST
          content:
            application/json:
              schema:
                type: object
                description: |-
                  Available messages:

                  • BAD_REQUEST
                properties:
                  message:
                    type: string
                  success:
                    type: boolean
                required:
                  - message
                  - success
        "403":
          description: |-
            Available messages:

            • FORBIDDEN
          content:
            application/json:
              schema:
                type: object
                description: |-
                  Available messages:

                  • FORBIDDEN
                properties:
                  message:
                    type: string
                  success:
                    type: boolean
                required:
                  - message
                  - success
        "404":
          description: |-
            Available messages:

            • USER_NOT_FOUND
          content:
            application/json:
              schema:
                type: object
                description: |-
                  Available messages:

                  • USER_NOT_FOUND
                properties:
                  message:
                    type: string
                  success:
                    type: boolean
                required:
                  - message
                  - success
  /account:
    get:
      tags:
        - user
      description: Get account
      security:
        - bearer: []
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    additionalProperties: false
                    properties:
                      id:
                        type: string
                        format: uuid
                      email:
                        type: string
                        format: email
                      name:
                        type: string
                        minLength: 1
                        maxLength: 255
                      method:
                        type: string
                        enum:
                          - email
                          - google
                      phoneNumber:
                        type: string
                        minLength: 1
                        maxLength: 255
                    required:
                      - id
                      - email
                      - name
                      - method
                      - phoneNumber
                  success:
                    type: boolean
                required:
                  - success
        "401":
          description: |-
            Available messages:

            • UNAUTHORIZED
          content:
            application/json:
              schema:
                type: object
                description: |-
                  Available messages:

                  • UNAUTHORIZED
                properties:
                  message:
                    type: string
                  success:
                    type: boolean
                required:
                  - message
                  - success
        "404":
          description: |-
            Available messages:

            • USER_NOT_FOUND
          content:
            application/json:
              schema:
                type: object
                description: |-
                  Available messages:

                  • USER_NOT_FOUND
                properties:
                  message:
                    type: string
                  success:
                    type: boolean
                required:
                  - message
                  - success
  /update-user:
    patch:
      tags:
        - user
      description: Update user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                email:
                  type: string
                  format: email
                name:
                  type: string
                  minLength: 1
                  maxLength: 255
                phoneNumber:
                  type: string
                  minLength: 1
                  maxLength: 255
                password:
                  type: string
                  minLength: 8
                  maxLength: 32
                  pattern: ^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d!@#$%^&*()-_=+\\|{}\[\];:,.<>\/?`~]+$
      security:
        - bearer: []
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    additionalProperties: false
                    properties:
                      id:
                        type: string
                        format: uuid
                      email:
                        type: string
                        format: email
                      name:
                        type: string
                        minLength: 1
                        maxLength: 255
                      method:
                        type: string
                        enum:
                          - email
                          - google
                      phoneNumber:
                        type: string
                        minLength: 1
                        maxLength: 255
                    required:
                      - id
                      - email
                      - name
                      - method
                      - phoneNumber
                  success:
                    type: boolean
                required:
                  - success
        "400":
          description: |-
            Available messages:

            • BAD_REQUEST
          content:
            application/json:
              schema:
                type: object
                description: |-
                  Available messages:

                  • BAD_REQUEST
                properties:
                  message:
                    type: string
                  success:
                    type: boolean
                required:
                  - message
                  - success
        "401":
          description: |-
            Available messages:

            • UNAUTHORIZED
          content:
            application/json:
              schema:
                type: object
                description: |-
                  Available messages:

                  • UNAUTHORIZED
                properties:
                  message:
                    type: string
                  success:
                    type: boolean
                required:
                  - message
                  - success
        "403":
          description: |-
            Available messages:

            • FORBIDDEN
          content:
            application/json:
              schema:
                type: object
                description: |-
                  Available messages:

                  • FORBIDDEN
                properties:
                  message:
                    type: string
                  success:
                    type: boolean
                required:
                  - message
                  - success
        "404":
          description: |-
            Available messages:

            • USER_NOT_FOUND
          content:
            application/json:
              schema:
                type: object
                description: |-
                  Available messages:

                  • USER_NOT_FOUND
                properties:
                  message:
                    type: string
                  success:
                    type: boolean
                required:
                  - message
                  - success
servers:
  - url: http://localhost:3000
tags:
  - name: user
